export default {
  ACTIONS: {
    ADD_TRANSACTION: 'ADD_TRANSACTION',
    CHANGE_TRANSACTION: 'CHANGE_TRANSACTION',
    DELETE_TRANSACTION: 'DELETE_TRANSACTION',
    ADD_CATEGORY: 'ADD_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    CHANGE_ALL_CATEGORIES: 'CHANGE_ALL_CATEGORIES',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    ADD_MONTH_COURSE: 'ADD_MONTH-COURSE',
    CHANGE_THEME: 'CHANGE_THEME',
  },
};
