const pallet = [
  {
    name: 'volta',
    alias: 'volta',
    background: '#842448',
    startColor: '#c04848',
    endColor: '#480048',
  },
  {
    name: 'purple bliss',
    alias: 'purple-bliss',
    background: '#204363',
    startColor: '#360033',
    endColor: '#0b8793',
  },
  {
    name: 'love couple',
    alias: 'love-couple',
    background: '#614362',
    startColor: '#89253e',
    endColor: '#3a6186',
  },
  {
    name: 'deep space',
    alias: 'deep-space',
    background: '#212121',
    startColor: '#434343',
    endColor: '#000',
  },
  {
    name: 'curiosity blue',
    alias: 'curiosity-blue',
    background: '#476283',
    startColor: '#3d72b4',
    endColor: '#525252',
  },
  {
    name: 'orca',
    alias: 'orca',
    background: '#266b62',
    startColor: '#093637',
    endColor: '#44a08d',
  },
  {
    name: 'love tonight',
    alias: 'love-tonight',
    background: '#7a69c7',
    startColor: '#4568dc',
    endColor: '#b06ab3',
  },
  {
    name: 'love and liberty',
    alias: 'love-and-liberty',
    background: '#641e2e',
    startColor: '#a83b3b',
    endColor: '#200122',
  },
  {
    name: 'blue lagoon',
    alias: 'blue-lagoon',
    background: '#2e6e80',
    startColor: '#43c6ac',
    endColor: '#191654',
  },
  {
    name: 'grapefruit sunset',
    alias: 'grapefruit-sunset',
    background: '#bc596c',
    startColor: '#904e95',
    endColor: '#e96443',
  },
  {
    name: 'frost',
    alias: 'frost',
    background: '#00295d',
    startColor: '#004e92',
    endColor: '#000428',
  },
  {
    name: 'mauve',
    alias: 'mauve',
    background: '#5a3963',
    startColor: '#734b6d',
    endColor: '#42275a',
  },
  {
    name: 'vice city',
    alias: 'vice-city',
    background: '#9081c9',
    startColor: '#ec6ead',
    endColor: '#3494e6',
  },
  {
    name: 'mild',
    alias: 'mild',
    background: '#59aa9e',
    startColor: '#4ca2cd',
    endColor: '#67b26f',
  },
  {
    name: 'nepal',
    alias: 'nepal',
    background: '#825ca6',
    startColor: '#2657eb',
    endColor: '#de6161',
  },
  {
    name: 'ibiza sunset',
    alias: 'ibiza-sunset',
    background: '#f6393c',
    startColor: '#ff6a00',
    endColor: '#ee0979',
  },
  {
    name: 'sunset',
    alias: 'sunset',
    background: '#805541',
    startColor: '#f56217',
    endColor: '#0b486b',
  },
  {
    name: 'colored lenses',
    alias: 'colored-lenses',
    background: '#a59db2',
    startColor: '#636fa4',
    endColor: '#e8cbc0',
  },
  {
    name: 'disco',
    alias: 'disco',
    background: '#51979a',
    startColor: '#556270',
    endColor: '#4ecdc4',
  },
  {
    name: 'dania',
    alias: 'dania',
    background: '#9cacc8',
    startColor: '#7bc6cc',
    endColor: '#be93c5',
  },
  {
    name: 'very blue',
    alias: 'very-blue',
    background: '#0348af',
    startColor: '#0575e6',
    endColor: '#021b79',
  },
  {
    name: 'cosmic fusion',
    alias: 'cosmic-fusion',
    background: '#9919b2',
    startColor: '#f0c',
    endColor: '#339',
  },
  {
    name: 'firewatch',
    alias: 'firewatch',
    background: '#dd3a3c',
    startColor: '#ef473a',
    endColor: '#cb2d3e',
  },
  {
    name: 'lush',
    alias: 'lush',
    background: '#7fc549',
    startColor: '#56ab2f',
    endColor: '#a8e063',
  },
  {
    name: 'transfile',
    alias: 'transfile',
    background: '#7077b1',
    startColor: '#cb3066',
    endColor: '#16bffd',
  },
  {
    name: 'red ocean',
    alias: 'red-ocean',
    background: '#603e40',
    startColor: '#a43931',
    endColor: '#1d4350',
  },
  {
    name: 'easy med',
    alias: 'easy-med',
    background: '#81b23e',
    startColor: '#409c43',
    endColor: '#c2c93a',
  },
  {
    name: 'cocoa ice',
    alias: 'cocoa-ice',
    background: '#6ed0bc',
    startColor: '#1ce1ce',
    endColor: '#c0c0aa',
  },
  {
    name: 'dark skies',
    alias: 'dark-skies',
    background: '#395b79',
    startColor: '#283e51',
    endColor: '#4b79a1',
  },
  {
    name: 'forest',
    alias: 'forest',
    background: '#435b3d',
    startColor: '#2c7744',
    endColor: '#5a3f37',
  },
];

export default pallet;
